
#coding:gbk
"""
第一个小项目：rock石头-paper纸-scissors剪刀-lizard蜥蜴-Spock史波克
作者：梁鹤逸
日期：2019.11.13
"""
# 0 - 石头
# 1 - 史波克
# 2 - 纸
# 3 - 蜥蜴
# 4 - 剪刀
import random
tag=1
list1=['石头','史波克','纸','蜥蜴','剪刀']
# 对程序进行测试
def name_to_number(name):#将用户的游戏选择对象转换为相应的整数
    if name=='石头':
       return 0
    elif name=='史波克':
       return 1
    elif name=='纸':
       return 2
    elif name=='蜥蜴':
       return 3
    elif name=='剪刀':
       return 4
    else:
       print('Error: No Correct Name')

def number_to_name(number):
    if number in range(0,5):
      if number==0:
        return 石头
      elif number==1:
        return 史波克
      elif number==2:
        return 纸
      elif number==3:
        return 蜥蜴
      elif number==4:
        return 剪刀
      else:
         print('Error: No Correct Name')
def rpsls(player_choice,computer):#用户玩家任意给出一个选择，根据RPSLS游戏规则，在屏幕上输出对应的结果
    while tag:
      list1=['石头','史波克','纸','蜥蜴','剪刀']
      list2=[[0,4],[0,3],[1,4],[1,0],[2,0],[2,1],[3,2],[3,1],[4,3],[4,2]]
      if player_choice in list1:
         if [player_choice,computer]in list2:
            print('您赢了')
         elif player_choice==computer:
            print('您和计算机出的一样呢')
         else:
            print('计算机赢了')
      else:
         print('Error: No Correct Name')
      break
print("欢迎使用RPSLS游戏")
print("----------------")
print("请输入您的选择:")
player_choice=input()
print("--------")
computer=random.choice(list1)
print('你的选择为:%s'%(player_choice))
print('计算机的选择为:%s'%(computer))
rpsls(player_choice,computer)#rpsls意为石头剪刀布
    


    # 输出"-------- "进行分割
    # 显示用户输入提示，用户通过键盘将自己的游戏选择对象输入，存入变量player_choice

    # 调用name_to_number()函数将用户的游戏选择对象转换为相应的整数，存入变量player_choice_number

    # 利用random.randrange()自动产生0-4之间的随机整数，作为计算机随机选择的游戏对象，存入变量comp_number

    # 调用number_to_name()函数将计算机产生的随机数转换为对应的游戏对象

    # 在屏幕上显示计算机选择的随机对象

    # 利用if/elif/else 语句，根据RPSLS规则对用户选择和计算机选择进行判断，并在屏幕上显示判断结果

    # 如果用户和计算机选择一样，则显示“您和计算机出的一样呢”，如果用户获胜，则显示“您赢了”，反之则显示“计算机赢了”

    #根据以上提示编写执行代码，代码完成后删除掉pass
#list2=[[0,4],[0,3],[1,4],[1,0],[2,0],[2,1],[3,2],[3,1],[4,3],[4,2]]
#[['石头','剪刀'],['石头','蜥蜴'],['史波克','剪刀'],['史波克','石头'],['布','石头'],['布','史波克'],['蜥蜴','布'],['蜥蜴','史波克'],['剪刀','蜥蜴'],['剪刀','布']]
